name: Publish to JSR on Release

on:
  workflow_run:
    workflows: ["Generate Release on Merge"]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    # Only publish if generate release was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
